#!/usr/bin/env bash
set -e
HERE=$(dirname $(realpath $0))
ROOT=$(dirname $HERE)
DEST="$ROOT/shared/.vault_token"
vault login -method=github -token-only > "$ROOT/shared/.vault_token"
echo "Vault token saved to $DEST"
