#!/usr/bin/env bash
set -e
HERE=$(dirname $(realpath $0))
ROOT=$(dirname $HERE)
DEST="$ROOT/shared/.vault_token"
VAULT_ADDR=https://vault.dide.ic.ac.uk
vault login -method=github -token-only > "$ROOT/shared/.vault_token"
echo "Vault token saved to $DEST"
